# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_WP9f1iW7qOFo8-pAfrCklNge_sknRE
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
# %matplotlib inline

data = pd.read_csv("/content/sample_data/mnist_train_small.csv")

data.head()

a = data.iloc[3,1:].values

a = a.reshape(28,28).astype('uint8')
plt.imshow(a)

df_x = data.iloc[:,1:]
df_y = data.iloc[:,0]

x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=4)

y_train.head()

rf = RandomForestClassifier(n_estimators=100)

rf.fit(x_train,y_train)

res = rf.predict(x_test)

y = y_test.values

count = 0

for i in range(len(y)):
    if res[i] == y[i]:
        count+=1

a = str(round((count/len(y)),4)*100)+"%"
print("Out of",len(y),"responses,",count,"responses are calculated correctly by RF Classifier.")
print("In other words, the accuracy of Random Forest Classifier is:",a)

from sklearn.svm import SVC

svm = SVC()

svm.fit(x_train,y_train)

y_svm_pred = svm.predict(x_test)

y = y_test.values

count = 0

for i in range(len(y)):
    if y_svm_pred[i] == y[i]:
        count+=1

b = str(round((count/len(y)),4)*100)+"%"
print("Out of",len(y),"responses,",count,"responses are calculated correctly by SV Classifier.")
print("In other words, the accuracy of Support Vector Classifier is:",b)

d = {"Random forest classifier":a, "Support Vector Classifier":b}
print("Algorithm               Accuracy")
for i in d.keys():
    print(i,d[i])